# Generated by Django 5.2.1 on 2025-05-14 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('reciclagem', 'Reciclagem'), ('cosméticos', 'Cosméticos'), ('velas', 'Velas'), ('crochê', 'Crochê'), ('bijuterias', 'Bijuterias')], max_length=100, unique=True)),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('preco', models.FloatField()),
                ('disponivel', models.BooleanField(default=True)),
                ('imagem', models.ImageField(upload_to='product_images/')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='market.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
